name: Post to Discord

on:
  push:
    paths:
      - 'posts/**'

jobs:
  post-to-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py

      - name: Post to Discord
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: |
          import discord
          import asyncio
          import os

          client = discord.Client(intents=discord.Intents.default())

          @client.event
          async def on_ready():
              channel = client.get_channel(int(os.environ['DISCORD_CHANNEL_ID']))
              changed_files = '${{ steps.changed-files.outputs.all_changed_files }}'.split()
              
              for file in changed_files:
                  if file.startswith('posts/') and file.endswith('.md'):
                      with open(file, 'r') as f:
                          content = f.read()
                      message = f"@everyone\n\n{content}"
                      await channel.send(message)
              
              await client.close()

          client.run(os.environ['DISCORD_BOT_TOKEN'])
        shell: python
